### ISSUE TITLE
Validation blocks csv update of samples

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/client_helpers#81] opened 2018-10-30 18:17 UTC
It should be possible to update an existing sample with information uploaded from a csv file. Because we are performing an update, the sample must already contain values for all the mandatory fields. However the process baulks in two ways if the csv file omits mandatory data.

Firstly, the user interface continues to show required fields and does not enable the upload button after selecting an update method.
![sample-update](https://user-images.githubusercontent.com/2545390/47740190-1fee6d80-dc6f-11e8-9252-0a655fe4ced3.PNG)

Secondly (having hacked the html to enable the upload button) the warehouse rejects the sample upload. In the errors.csv it complains about a missing sample attribute which is required but, in the log there is more:
```
2018-10-30 17:47:36 +00:00 --- debug: Record did not validate
2018-10-30 17:47:36 +00:00 --- debug: Field date_type: Please supply a date for your observation.
2018-10-30 17:47:36 +00:00 --- debug: Field entered_sref: The spatial reference must be supplied.
2018-10-30 17:47:36 +00:00 --- debug: Field entered_sref_system: The spatial reference system must be supplied.
2018-10-30 17:47:36 +00:00 --- debug: Field geom: The spatial reference must be supplied.
2018-10-30 17:47:36 +00:00 --- debug: No value for Honey time at location in Array

```
This is not behaviour I would expect.

**Comment by johnvanbreda** [comment] 2018-11-07 09:57
Hi @JimBacon, I think this is now fixed, but will let you test to confirm. Here's a description of my test scenario:

On the test warehouse, there is a website called Import test, containing a single survey. This is a standard survey setup with a single sample custom attribute called Identified by, which is required. You can import a single sample into the survey using the following CSV (sorry, can't upload CSV files for some reason - not an accepted extension):

```csv
Date,Grid ref,External key,Identified by,Sample method
11/05/2018,SY9997,ABC123,John,Field Observation
```

Now, you can import the following CSV to update the same record. This has a missing grid ref and identified by field, both of which should fail validation if the code doesn't take them from the existing record.:

```csv
External key,Date,Sample method
ABC123,01/01/2015,Field Observation
```

Things I've done:
* The first thing to note is I've fixed the UI to allow you to bypass the required field checks when you have set up an existing record lookup. It will display a message explaining this when it happens.
* I've also fixed a few bugs - I couldn't get the code working initially, e.g. it would never enable the drop down to select the fields you want to lookup against.
* I've done quite a lot of code tidying - moving a lot of JS to a file, rather than injecting it inline.
* I've changed the column which shows when a field is included in the lookup of existing records - showing a tick where relevant rather than a disabled checkbox, as the latter had made me think that I should do something to enable the checkboxes so I could tick them.

Having done all that, I had hoped that my test scenario would come up against the 2nd problem you listed - that of server-side validation. But it seems to work OK and I've checked through the code which does seem to cover this scenario. So, I couldn't reproduce the server side validation problem.

I've also added a test to the PHPUnit test cases to cover the partial update scenario.

**Comment by johnvanbreda** [comment] 2018-12-17 15:27
Fixed, released and tested in v2.

**Closed as completed by johnvanbreda** 2018-12-17 15:27 UTC
