### ISSUE TITLE
"Other" freetext field not working for drop-down control type

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#83] opened 2018-11-02 16:37 UTC
When using the "Other" option for a termlist based control on a data entry form, it does not currently work if the control type is a drop-down list.
If an "Other" option is setup, it should result in the display of an extra field for the entry of additional information but this fails to work for this control type.

**Comment by JimBacon** [comment] 2021-11-11 14:57
Duplicate of #82

**Closed as completed by JimBacon** 2021-11-11 14:57 UTC
